# -*- coding: utf-8 -*-
"""duke_energy_data_part02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jgmNeRWeLPTqnw5dhnWdTBl7ZcKf2wz6

## Objectives

1. Understand how a ts dataset can be converted to a cross sectional dataset. We will do this:  
  + By hand  
  + MLForecast library

2. Explore a sample of popular "ML" models for forecasting:  
  + `lasso`
  + `knn`
  + `RandomForest`
  + `lightgbm`

# Library Imports and Installations
"""

# !pip install statsforecast mlforecast utilsforecast coreforecast

import pandas as pd

from sklearn.linear_model import Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from lightgbm import LGBMRegressor

from mlforecast import MLForecast
from mlforecast.lag_transforms import RollingMean

from utilsforecast.evaluation import evaluate
from utilsforecast.losses import mape, rmse

"""# Read the Data"""

df = pd.read_csv("/content/merged_duke_data.csv")

df = (
    df
    .assign(
        ds = lambda x: pd.to_datetime(x["ds"]),
        day_of_week = lambda x: x['day_of_week'].astype('category'),
        month = lambda x: x['month'].astype('category'),
        holiday_name = lambda x: x['holiday_name'].astype('category')
    )
)

# create lags 28:55 using a for loop and a f-string (create diff variable names)
# for i in range(28,56):
#     df[f'lag{i}'] = df['y'].shift(i)

# df = df.dropna() # got introduced by the lag

df = pd.get_dummies(df, columns=['day_of_week', 'month', 'holiday_name'], drop_first=True)

display(df)

"""# Typical Nixtla Pipeline

1. Load the Models
2. Initiate the `MLForecast` object
3. Apply cross validation on that object
"""

ml_models = {
    "lasso": Lasso(),
    "knn": KNeighborsRegressor(),
    "random_forest": RandomForestRegressor(),
    "lightgbm": LGBMRegressor()
}

mlf = MLForecast(
    models = ml_models,
    freq= 'D',
    lags = range(28, 56), # 4 weeks worth of lags
    lag_transforms= {
        28 : [
            RollingMean(window_size=7), # avg y from t-28 to t-34 [7 day average of what happened 5 weeks ago],
            RollingMean(window_size=14), # avg y from t-28 to t-42 [14 day average of what happened 5 weeks ago],
        ]
    },
    date_features= ['year'] # we already have week_day and month
)

cross_validation_mlf = mlf.cross_validation(
    df = df,
    n_windows= 12,
    h = 28,
    step_size = 28,
    static_features=[]
)

display(cross_validation_mlf)

eval_ml = evaluate(
    df = cross_validation_mlf,
    metrics = [mape, rmse],
    models = ['lasso', 'knn', 'random_forest', 'lightgbm']
)

eval_ml